echo Inventory Update Process is executing...
cd D:\CSE5234_Group1-master\batch 
"C:\Program Files\Java\jdk1.8.0_91\bin\java" -classpath D:\CSE5234_Group1-master\batch\h2-1.4.196.jar; edu.osu.cse5234.batch.InventoryUpdater 
echo Inventory Update completed...
pause